language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jakethecoder/udemy-docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true jakethecoder/udemy-docker-react npm run test